### ISSUE TITLE
Bootstrap 4 wishlist

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#884]
* [x] convert CSS to SCSS
* [ ] get the menu bar straight. right now it breaks e.g. anchors (#539), and it does not properly transition into hamburger menu (#512)
* [ ] keep mobile-friendliness in mind when upgrading (#883)
* [ ] ~put email form (on status change pages) in collapsible that toggles with enabling and disabling the email notifications~ *won't fix*
* [x] update label colors (info and primary are almost the same)
* [ ] validate #916, maybe it fixes itself

bootstrap blog: https://blog.getbootstrap.com/
